dataset_name: 'discharge'

epoch: 50
batch_size: 32
loss_fn: mse_loss
scale: True
scaling_axis: 'channels'

model_name: 'tcn'
input_size: 24
output_size: 24
num_channels: [32, 64, 128]
d_hidden: 128
kernel_size: 3
inject_noise: true
dropout: 0.2
